# -*- coding: utf-8 -*-
"""genai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vdscp9ys7qzNZkgXtXboHLSdcwxcjPvw
"""

import subprocess
import sys


from langchain_huggingface import ChatHuggingFace

from langchain_core.messages import chat
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer
import torch

model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# Explicitly load model and tokenizer for causal language modeling
tokenizer = AutoTokenizer.from_pretrained(model_id)
# Using torch_dtype=torch.bfloat16 for better performance on compatible hardware, or 'auto'
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.bfloat16)

# Create the pipeline
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=100,
    temperature=0.7
)

# Pass the created pipeline to HuggingFacePipeline
llm = HuggingFacePipeline(pipeline=pipe)
chat_model = ChatHuggingFace(llm=llm)

result=chat_model.invoke("what is data science")
print(result.content)

